command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "SERVING_ENDPOINT"
    value: "https://adb-3997317045094469.9.azuredatabricks.net/serving-endpoints/databricks-dbrx-instruct"
